import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VoiceCode",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html class="dark" lang="en">
      <body class="h-screen" className={inter.className}>
        {children}
      </body>
    </html>
  );
}
